version: '3.9'

services:
  web-dev:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env

  db-dev:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data_dev: