services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn kevinpwhite.wsgi:application --bind 0.0.0.0:443
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 443
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 3004:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  